### ISSUE TITLE
Undefined method `change_contents` for RubyXL::Cell 

### ISSUE THREAD

**Issue by rockorequin** [weshatheleopard/rubyXL#330]
Using rubyXL 3.4.2 or 3.4.0 and either ruby 2.6.2 or 2.5.3, this code causes an exception:
```
require 'rubyXL'
workbook = RubyXL::Workbook.new
worksheet = workbook[0]
worksheet.add_cell 0, 0, 'hi'
worksheet[0][0].change_contents 'there'
```

The exception is:

```
NoMethodError (undefined method `change_contents' for #<RubyXL::Cell(0,0): "hi", datatype="str", style_index=0>)
```

The code works fine in rubyXL 3.3.33. Did the spec change for 3.4.0? (The README.rdoc still specifies the change_contents method.)

**Comment by weshatheleopard** [comment]
README.rdoc also has a new section added explicitly mentioning 3.4.0 and what should you do.
