### ISSUE TITLE
 Error: undefined method

### ISSUE THREAD

**Issue by tippexs** [weshatheleopard/rubyXL#398]
Using Ruby 2.5.0 with Rails 5.2.5

RubyXL Version: 
` rubyXL (3.4.17)`
Gemfile.lock
```
    rubyXL (3.4.17)
      nokogiri (>= 1.10.8)
      rubyzip (>= 1.3.0)
```

I have a sidekiq worker task creating a XLS-Sheet:
```
module WorkerXlsxOutput
  def xlsx_file_name
    raise "xlsx_file_name has to be defined in #{self}"
  end

  def xlsx_headers
    raise "xlsx_headers has to be defined in #{self}"
  end

  def xlsx_values
    raise "xlsx_values has to be defined in #{self}"
  end

  def create_spreadsheet
    book = RubyXL::Workbook.new
    sheet1 = book.worksheets[0]

    insert_xlsx_headers(sheet1)
    insert_values(sheet1)

    book.write xlsx_file_name
  end

  def header_row_defaults(sheet)
    sheet.change_row_fill(0, '000000')
    sheet.change_row_font_color(0, 'ffffff')
  end

  def header_cell_defaults(cell)
    cell.change_text_wrap(true)
    cell.change_horizontal_alignment('center')
    cell.change_vertical_alignment('center')
  end

  def content_cell_defaults(cell, value)
    cell.change_text_wrap(true)
    cell.change_contents(value, cell.formula)
    cell.change_vertical_alignment('top')
  end

  def insert_xlsx_headers(sheet)
    header_row_defaults(sheet)
    xlsx_header_values.each_with_index do |header, index|
      sheet.add_cell(0, index, header[:text])
      sheet.change_column_width(index, header[:width])
      header_cell_defaults sheet[0][index]
    end
  end

  def insert_values(sheet)
    xlsx_values.each_with_index do |row, row_index|
      row.each_with_index do |value, col_index|
        sheet.add_cell(row_index + 1, col_index, '')
        sheet[row_index + 1][col_index].set_number_format('m:ss') if col_index == 12
        content_cell_defaults sheet[row_index + 1][col_index], value
      end
    end
  end
end

```

In my Sidekiq console I am getting the following erros since 3.4. It was working with 3.3.

```
E, [2021-05-10T16:03:25.807545 #25846] ERROR -- : Error: undefined method `change_column_width' for #<RubyXL::Worksheet:0x000055a89aa86ab8> (NoMethodError)Backtrace:
/var/opt/webapps/company/staging/releases/20210506165136/app/jobs/worker_xlsx_output.rb:45:in `block in insert_xlsx_headers'
        /var/opt/webapps/company/staging/releases/20210506165136/app/jobs/worker_xlsx_output.rb:43:in `each'
        /var/opt/webapps/company/staging/releases/20210506165136/app/jobs/worker_xlsx_output.rb:43:in `each_with_index'
        /var/opt/webapps/company/staging/releases/20210506165136/app/jobs/worker_xlsx_output.rb:43:in `insert_xlsx_headers'
        /var/opt/webapps/company/staging/releases/20210506165136/app/jobs/worker_xlsx_output.rb:18:in `create_spreadsheet'
        /var/opt/webapps/company/staging/releases/20210506165136/app/workers/export/metadata/xlsx_commons.rb:8:in `run'
        /var/opt/webapps/company/staging/shared/bundle/ruby/2.5.0/gems/worker_tools-0.2.1/lib/worker_tools/basics.rb:37:in `block in perform'
        /var/opt/webapps/company/staging/shared/bundle/ruby/2.5.0/gems/worker_tools-0.2.1/lib/worker_tools/basics.rb:79:in `with_wrappers'
        /var/opt/webapps/company/staging/shared/bundle/ruby/2.5.0/gems/worker_tools-0.2.1/lib/worker_tools/basics.rb:82:in `block in with_wrappers'
        /var/opt/webapps/company/staging/shared/bundle/ruby/2.5.0/gems/worker_tools-0.2.1/lib/worker_tools/recorder.rb:4:in `with_wrapper_recorder'
        /var/opt/webapps/company/staging/shared/bundle/ruby/2.5.0/gems/worker_tools-0.2.1/lib/worker_tools/basics.rb:82:in `with_wrappers'
        /var/opt/webapps/company/staging/shared/bundle/ruby/2.5.0/gems/worker_tools-0.2.1/lib/worker_tools/basics.rb:82:in `block in with_wrappers'
        /var/opt/webapps/company/staging/shared/bundle/ruby/2.5.0/gems/worker_tools-0.2.1/lib/worker_tools/basics.rb:51:in `with_wrapper_basics'
        /var/opt/webapps/company/staging/shared/bundle/ruby/2.5.0/gems/woraker_tools-0.2.1/lib/worker_tools/basics.rb:82:in `with_wrappers'
        /var/opt/webapps/company/staging/shared/bundle/ruby/2.5.0/gems/worker_tools-0.2.1/lib/worker_tools/basics.rb:36:in `perform'
        /var/opt/webapps/company/staging/shared/bundle/ruby/2.5.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:196:in `execute_job'
        /var/opt/webapps/company/staging/shared/bundle/ruby/2.5.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
        /var/opt/webapps/company/staging/shared/bundle/ruby/2.5.0/gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
        /var/opt/webapps/company/staging/shared/bundle/ruby/2.5.0/gems/sentry-raven-3.1.2/lib/raven/integrations/sidekiq/cleanup_middleware.rb:7:in `call'
        /var/opt/webapps/company/staging/shared/bundle/ruby/2.5.0/gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:140:in `block in invok
```

On the deployment server I am able to use the Rails console without any errors:

```
    book = RubyXL::Workbook.new
    sheet1 = book.worksheets[0]

2.5.0 :005 > sheet.change_row_fill(0, '000000')
 => [] 
2.5.0 :006 >
```

My Gems are auto-load in my boot.rb 
```
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', __dir__)

require 'bundler/setup' # Set up gems listed in the Gemfile.
require 'bootsnap/setup' # Speed up boot time by caching expensive operations.

```

Any idea why my tasks are failing since version 3.4.17?

**Comment by tippexs** [comment]
Hi @weshatheleopard . Thats what I did before I posted this issue. I have added the lines in my module
```
require 'rubyXL/convenience_methods/cell'
require 'rubyXL/convenience_methods/color'
require 'rubyXL/convenience_methods/font'
require 'rubyXL/convenience_methods/workbook'
require 'rubyXL/convenience_methods/worksheet'

module WorkerXlsxOutput

....
```

Sorry for copying the wrong file content. Is there anything wrong with the require in my code block?

**Comment by marvellouschandan** [comment]
Thank you @weshatheleopard , adding below line to my code worked.

```ruby
require 'rubyXL/convenience_methods'
```
