### ISSUE TITLE
undefined method `fill_color' for #<RubyXL::Cell(1,5): nil, datatype=nil, style_index=30> (NoMethodError)

### ISSUE THREAD

**Issue by Souravgoswami** [weshatheleopard/rubyXL#417]
I used the gem version 3.3.33, where it's giving me this error:

```
/home/sourav/.gem/ruby/3.0.0/gems/rubyXL-3.4.10/lib/rubyXL/objects/text.rb:89:in `block in to_s': can't modify frozen String: "" (FrozenError)
```
It's because nil.to_s in Ruby 2.7 is returning frozen string.

So I tried updating to the latest version 3.4.22 where the problem is apparently fixed, now I'm getting this error:

```
xlsx_to_yaml_rubyXL.rb:80:in `block (3 levels) in <main>': undefined method `fill_color' for #<RubyXL::Cell(1,5): nil, datatype=nil, style_index=30> (NoMethodError)
```

I know something has changed, but I can't find the fill_color method which I used to detect the background colour of the cell.

Any ideas where did the fill_color go? I can't find it in get_* methods. No documentation either. Can only get the font colour now :(

**Comment by weshatheleopard** [comment]
It's in the [documentation](https://github.com/weshatheleopard/rubyXL#label-Convenience+methods).

**Comment by Souravgoswami** [comment]
Well as I said, `cell.fill_color` doesn't work on newer versions. It worked in the older version 3.3.33 and those.

**Comment by weshatheleopard** [comment]
You are not much of a reader, are you?

```
> require 'rubyXL'
> require 'rubyXL/convenience_methods'
> workbook = RubyXL::Workbook.new
> cell = workbook[0].add_cell(0,0)
> cell.fill_color
 => "ffffff"
```

**Comment by Souravgoswami** [comment]
Sorry, don't want to argue of course, you know it better.

I was trying to say that:

![image](https://user-images.githubusercontent.com/37468605/158908539-63ce9e99-cad3-4894-a6fd-f827f54e5b05.png)

On the above, I have 3.3.33, and on the bottom I have 3.4.22.

Not sure about add_cell(0, 0), but documentation says it's under "Modifying" category. I don't want to modify my spreadsheet, but just read the cells and read the background colour. Because in my case, the background colour determines boolean values!

**Comment by weshatheleopard** [comment]
Ummm, hello? Where's `require 'rubyXL/convenience_methods'`?

**Comment by Souravgoswami** [comment]
Yup, sorry, it works now. Wasn't aware of that separate method. Makes sense it reduces the memory footprint. Thank you very much!
